# -*- coding: utf-8 -*-
"""Music Recommendation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plHipMS4i4D7AdLUMmDsvrRw749NECDK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.manifold import TSNE

import warnings
warnings.filterwarnings('ignore')

tracks = pd.read_csv('/content/dataset.csv.zip')
tracks.head()

tracks.shape

tracks.info()

tracks.isnull().sum()

tracks.dropna(inplace = True)
tracks.isnull().sum().plot.bar()
plt.show()

tracks = tracks.drop(['track_id', 'artists'], axis = 1)

# Select only numerical columns for t-SNE
numeric_tracks = tracks.select_dtypes(include=['number'])
model = TSNE(n_components = 2, random_state = 0)
tsne_data = model.fit_transform(numeric_tracks.head(500))

plt.figure(figsize = (7, 7))
plt.scatter(tsne_data[:,0], tsne_data[:,1])
plt.show()

tracks['track_name'].nunique(), tracks.shape

tracks = tracks.sort_values(by=['popularity'], ascending=False)
tracks.drop_duplicates(subset=['track_name'], keep='first', inplace=True)

plt.figure(figsize = (10, 5))
sb.countplot(tracks['duration_ms'])
plt.axis('off')
plt.show()